export type ChartTypes =
  | 'line'
  | 'smoothLine'
  | 'area'
  | 'stackedArea'
  | 'stackedArea100'
  | 'column'
  | 'stackedColumn'
  | 'stackedColumn100'
  | 'bar'
  | 'stackedBar'
  | 'stackedBar100'
  | 'pie'
  | 'ring'
  | 'scatter'
