export const postgresColumnTypes = {
  bigint: 'number',
  bigserial: 'serial',
  'bit varying': 'bit',
  bytea: 'binary',
  character: 'text',
  'character varying': 'text',
  'double precision': 'number',
  integer: 'number',
  numeric: 'number',
  real: 'number',
  smallint: 'number',
  smallserial: 'serial',
  timetz: 'timezone',
  'time without time zone': 'timestamp',
  'time with time zone': 'timestamp',
  'timestamp without time zone': 'timestamp',
  'timestamp with time zone': 'timestamp',
}
